services:
  mariadb:
    build:
      context: ./srcs/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - /home/tfauve-p/data/mariadb_data:/var/lib/mysql
    networks:
      - inception
    #restart: unless-stopped

  wordpress:
    build:
      context: ./srcs/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - /home/tfauve-p/data/wp_files:/var/www/html
    networks:
      - inception
    #restart: unless-stopped

  nginx:
    build:
      context: ./srcs/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - /home/tfauve-p/data/wp_files:/var/www/html
    networks:
      - inception
    #restart: unless-stopped
 
networks:
  inception:
    driver: bridge